site_name: AviUtl ExEdit2 Wiki

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/Hallkun19/Aviutl2Wiki
repo_name: Hallkun19/AviUtl2Wiki

theme:
  name: material
  logo: img/logo.png
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
  custom_dir: overrides

nav:
  - ホーム: index.md
  - はじめに:
      - 導入方法: contents/contents_how_to_install/how_to_install.md
      - 基本的な使い方: contents/contents_how_to_install/how_to_use.md

  - スクリプト / プラグイン:
      - 導入方法: contents/contents_script_and_plugin/how_to_install_script.md
      - 利用できるもの一覧: contents/contents_script_and_plugin/scripts.md
      - 投稿フォーム: contents/contents_script_and_plugin/script_post.md

  - スクリプト開発について:
      - SDKの利用方法: contents/contents_script_dev/sdk_usage.md
      - 拡張子ごとの機能差: contents/contents_script_dev/how_to_sdk_extension.md
      - 開発環境の作成: contents/contents_script_dev/how_to_sdk_dev_env.md

  - よくある質問:
      - よくある質問: faq.md
      - エラーコード: error_code.md
      - AviUtlとの違い: aviutl_diff.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - admonition
