site_name: AviUtl ExEdit2 Wiki

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/Hallkun19/Aviutl2Wiki
repo_name: Hallkun19/AviUtl2Wiki

theme:
  name: material
  logo: img/logo.png
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
  custom_dir: overrides

nav:
  - ホーム: index.md
  - はじめに:
    - 導入方法: how_to_install.md
    - 基本的な使い方: how_to_use.md

  - スクリプト: 
    - スクリプトの導入方法: how_to_install_script.md
    - AviUtl2でも使用できるスクリプト一覧: compatible_scripts.md
  - プラグイン:
    - プラグインの導入方法: how_to_install_plugin.md
    - AviUtl2でも使用できるプラグイン一覧: compatible_plugins.md
  - AviUtlとの違い: aviutl_diff.md
  - よくある質問: faq.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - admonition
  - pymdownx.emoji: